### ISSUE TITLE
Was the grid view removed from the pinned view

### ISSUE THREAD

**Issue by Wladefant** [FMaz008/VineHelper#147] opened 2024-10-05 11:55 UTC
### Feature Description

I did not find a way to turn it back on. I have a hundred pinned items, so a list view is quite longer than a grid view. Would definitely think it should be added back.

**Comment by FMaz008** [comment] 2024-10-05 12:43
Duplicate of https://github.com/FMaz008/VineHelper/issues/134#issue-2559901524

**Closed by FMaz008** 2024-10-05 12:43 UTC
Labels: enhancement
