### ISSUE TITLE
Not receiving notifications when new items are added even when turned on.

### ISSUE THREAD

**Issue by sorphin** [FMaz008/VineHelper#16] opened 2024-01-30 03:39 UTC
I've turned it on on 1.19 (and the clone from the repo). Today lots of new things were dropped and there were no notifications. On Chrome latest.

**Comment by FMaz008** [comment] 2024-01-30 11:08
Explainer how the system works, but I think you found a bug, just not an obvious one;


Notification system check every 60 seconds. You'll see a loading wheel to the bottom right of the screen showing it's looking for new items.

The system does not actually check for new items, but if other users have seen new items. Typically this happen fairly fast, but at least one person needs to see the new item(s) that YOU have not yet seen.

So say:
- a new item drop at 1:00:00
- your notification system check for new items at 1:00:30: nothing new was reported.
-  first user to sees it at 1:01:00
- the server record the item as new from 1:01:00

Now 2 scenarios:
A)
- your notification system check for new item at 1:01:30. New item found!

B)
- you refresh the page at 1:01:15, see the new item. Latest item you saw is updated to 1:01:15.
- your notification system check for new items at 1:01:30. It sees the new items from 1:01:00, but it is not newer than your most recent view of 1:01:15. No notification is shown.



With all that being said, I think there is a timezone issue. Where the time you last saw an item is store from your browser's time. The time of the reported items are server time. Pretty sure that's the problem.

**Comment by FMaz008** [comment] 2024-02-01 13:23
@sorphin Could you clarify if you had a bug or if it was just a missunderstanding of how the notifications work?

**Comment by sorphin** [comment] 2024-02-01 17:26
seems like a bug.. for example.. about an hour ago, I got up, went on vine, there were lots of yellow highlights, i went through everything. Set a new bookmark.  it's now an hour later.. the item count on vine has gone up a few hundred (for me in the US). No notifications... also not seeing any new yellow (which is strange since it seems to work sitting overnight).

**Comment by FMaz008** [comment] 2024-03-04 12:55
@sorphin Is the issue persisting?

**Comment by sorphin** [comment] 2024-03-05 18:25
I honestly turned off the notifications for new items because it was getting a bit spammy if during the drop and no info in the popup. However, I do still quite often have the issue of when i set bookmark, no notification pops up.. that's because fairly consistent now with only a few times it has worked,

**Comment by FMaz008** [comment] 2024-03-05 19:02
Ok, but this bug report was because notifications were not happening during drops.
Now you are saying they did showed up so much it was annoying (which, fair enough), but can I consider that your issue of not receiving notifications for new items was resolved since V 1.19 ?

You could re-open a new ticket for notifications not showing when setting the bookmark. I've noticed sometime (very rarely, but still) a tab will play a notification sound and not display a notification, so there might be a bug with the notification system itself, but I was not able to reproduce it reliably enough to get an error from the console. If you do, I'd love to know.

As for the useless nature of the notifications, I totally agree, and it should get a lot better in V2.1.0

**Comment by sorphin** [comment] 2024-03-05 19:05
They weren't coming in, then eventually did.. I don't know if they still would now or not, so I don't know if it was resolved as of 1.19 or not. I can turn them back on soon and see how it behaves I suppose. I'll see what/if I can notice anything with the sound/notification issue you mentioned above.

**Comment by FMaz008** [comment] 2024-03-05 19:09
Sounds good. Thank you for looking into it :)

I believe the detection for new items works well now (server-side), but that there may be a rare bug with the notification system itself (extension-side) (regardless of what triggers the notification).

Note that you should not receive notifications for items which are from the RFY queues anymore.

**Comment by FMaz008** [comment] 2024-03-11 13:56
I believe to have found the cause for this and the new versions should work just fine.

I'll close the issue but reopen one if this occur again

**Closed by FMaz008** 2024-03-11 13:56 UTC
