### ISSUE TITLE
All Hidden Items Lost after 1/28/2024 Update

### ISSUE THREAD

**Issue by PsyfireX** [FMaz008/VineHelper#9] opened 2024-01-28 12:16 UTC
Since the update on 1/28/2024, all items that were previously hidden were lost.

**Comment by FMaz008** [comment] 2024-01-28 12:37
Could you clarify what you mean by lost ? 
They reappeared in the Available tab?

V1.17 should have transferred all your hidden items from the settings to their own memory variable in local storage.
 It is possible that transfer did not complete successfully, but my test was showing if was working. How many items do you think you had hidden ? (like a few, or thousands?)

Are the hidden items now being added storing up properly?

**Comment by PsyfireX** [comment] 2024-01-29 02:42
I had hidden probably a couple thousand items before that update.  The "Dr Talbot's" being the most obvious ones in Available for All.

* I received a popup notifying me of the update. 
* I immediately noticed those "Dr Talbot's" items.
* I opened a several of my regular searches, and noticed nothing else was hidden, including items I know I previously hid.

Unfortunately, I imagine everything I previously hid by now is simply gone so there's probably no undoing that.  Though ideally it might be good to know how it happened to avoid a repeat.

> Are the hidden items now being added storing up properly?

Items I've hidden since that update remain hidden, and it continues to work the same way it did before.

**Comment by FMaz008** [comment] 2024-01-29 11:49
v 1.17 was supposed to **transfer** hidden items from the settings to their own variable in the local storage. Although the code looks good and I can't reproduce the issue, it is possible I messed that part, which would have caused a reset.

Do you think this is what happened, or did you experience loosing hidden items at version >=1.18 ?

In any case, and not ignoring this issue, the option to store hidden items on the server is coming soon, and this should be much more reliable as it will use a MySQL database.

**Comment by FMaz008** [comment] 2024-02-01 13:22
The management of hidden items was rehauled with a decidated manager class to deal with it. This is fixed.

**Closed by FMaz008** 2024-02-01 13:22 UTC
Labels: bug
