### ISSUE TITLE
Plugin Doesn't Handle Multiple Tabs Properly

### ISSUE THREAD

**Issue by PsyfireX** [FMaz008/VineHelper#11] opened 2024-01-28 12:23 UTC
Steps:

* Open two vine tabs, showing items at the same time.
* Hide an item in tab-1
* Hide a different item in tab-2
* Reload tab-1
* The item hidden in tab-1 will disappear

It appears that when a tab is opened, it loads hidden items into memory.  When an item is hidden, it updates the in-memory list, and overwrites whatever is saved with that in-memory list.

The primary problem is when opening multiple tabs (such as multiple searches) it's easy to accidentally overwrite recent changes in other tabs.

**Comment by FMaz008** [comment] 2024-01-28 12:29
This has been confirmed as an issue since hidden items were introduced, and the effect was further made worst with the addition of new items notifications in v.1.14.

It has been fixed as of v1.17 and published as an emergency fix.

**Comment by FMaz008** [comment] 2024-01-28 12:33
Fixed

**Comment by PsyfireX** [comment] 2024-02-01 17:05
The bug is still in "Amazon Vine Helper 1.19"

**Comment by PsyfireX** [comment] 2024-02-01 17:24
1) Open 2 tabs at the same time.  For example:

* https://www.amazon.com/vine/vine-items?search=pillow
* https://www.amazon.com/vine/vine-items?search=blanket

2) Hide some items in both tabs.  First tab 1 (pillow) then tab 2 (blanket)

![vinetabs-1](https://github.com/FMaz008/VineHelper/assets/5668884/265ee09b-fcef-4649-8091-9c9904ee669e)


3) reload both tabs

4) Observe how items in one of the tabs will not be hidden.  In this case, the first tab where items were hidden, because it appears to have been overwritten by tab-2's changes.

![vinetabs-2](https://github.com/FMaz008/VineHelper/assets/5668884/21f0eaac-3f29-4b1c-b0b2-b91ad58a11cf)

**Comment by PsyfireX** [comment] 2024-02-01 17:28
@FMaz008 Since I cannot re-open the bug, I'm tagging you.  (Apologies for any notification spam you may get).

**Comment by FMaz008** [comment] 2024-02-01 17:40
No problem. When you hide an item, it save the entire list over, not just add or delete the list (local storage does not allow that).

I suggest you turn on the remote saving in V2.0.

**Comment by PsyfireX** [comment] 2024-02-01 18:55
What about the following logic.  I'm using pseudocode here:

```
hideItem(id) {    
   localList = getListFromLocalStorage()  
   updated = local.add(id)      // whatever the append to list function is
   saveToLocalStorage(updated)
}

hideItem(id) {
   localList = getListFromLocalStorage()
   updated = local.remove(id)
   saveToLocalStorage(updated)
}

```

**Comment by FMaz008** [comment] 2024-02-01 19:07
You are 100% correct. Will implement that in the next few days

**Comment by FMaz008** [comment] 2024-02-01 19:40
This should do it for the next version:

https://github.com/FMaz008/VineHelper/commit/67b97fe4156594b9aa32497af9c7339c24d30688

**Comment by PsyfireX** [comment] 2024-02-01 22:24
Awesome!  I left a brief code-review comment, and am looking forward to the release!

**Comment by FMaz008** [comment] 2024-02-02 00:27
Fixed as per your comment. Should be good now :)

**Closed by FMaz008** 2024-02-02 00:27 UTC
Labels: bug
