### ISSUE TITLE
Hide Icon is no longer visible on icons.  

### ISSUE THREAD

**Issue by PsyfireX** [FMaz008/VineHelper#10] opened 2024-01-28 12:19 UTC
It appears you can still click where the "hide" icon is supposed to be to hide an item, however the icon itself is not visible.  The icons for show all and hide all also disappeared, although the text is still visible.

This broke during the 1/28/2024 Update.

**Comment by FMaz008** [comment] 2024-01-28 12:32
Duplicate of https://github.com/FMaz008/VineHelper/issues/7

Fixed in v1.19 which was published as an emergency fix.

**Closed by FMaz008** 2024-01-28 12:32 UTC
Labels: duplicate
